<h1 style="font-size:2.5em;text-align:center">Visual and Scientific Computing</h1>
<h2 style="text-align:center">Basics</h2>
<h3 style="text-align:center">SoSe 2020</h3>
<p style="text-align:justify">Das Lernziel dieser Übungsaufgabe ist mit der Programmiersprache Python und der Bibliothek Numpy vertraut zu werden, um diese dann als Werkzeug in den weiteren Übungen einzusetzen. Machen Sie sich deshalb bitte so gut es geht damit vertraut und nutzen Sie dafür auch bitte Online-Resourcen wie <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/">https://docs.scipy.org/doc/numpy-1.13.0/reference/</a> und <a href="https://docs.python.org/3/">https://docs.python.org/3/</a>.</p>

## Aufgabe 1: Python Einführung (5 Punkte)

<ol style="list-style: lower-alpha"><li>Um sich mit der Programmiersprache Python vertraut zu machen, implementieren Sie einen einfachen Mergesort-Algorithmus. Eine beispielhafte Eingabe und Ausgabe könnte so aussehen:</li></ol>
<pre>Eingabe: [ 5 14 10  7  2 13  1 12  6  9  0  3  8 11  4]
Ausgabe: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]</pre>

In [62]:
import numpy as np


def mergesort(liste: list) -> np.array:
    """
    Implements Mergesort using an list as input and
    returning a sorted list

    :param liste:
    :return: list
    """
    if len(liste) > 1:
        mid = int(len(liste) / 2)
        left = liste[:mid]
        right = liste[mid:]
        mergesort(left)
        mergesort(right)
        x = 0
        y = 0
        m = 0
        while x < len(left) and y < len(right):
            if left[x] <= right[y]:
                liste[m] = left[x]
                x += 1
            else:
                liste[m] = right[y]
                y += 1
            m += 1

        while x < len(left):
            liste[m] = left[x]
            x += 1
            m += 1

        while y < len(right):
            liste[m] = right[y]
            y += 1
            m += 1

        return liste

In [63]:
sorted_list = mergesort([52, 18, 65, 61, 31, 86, 36, 15, 22, 13])

print(sorted_list)

[13, 15, 18, 22, 31, 36, 52, 61, 65, 86]


## Aufgabe 2: Numpy Einführung (5 Punkte)

<p style="margin-left:2em">Die Bibliothek <em>Numpy</em> ist sehr umfangreich und wir werden auch nicht jede Funktionalität brauchen, aber es ist wichtig mit den grundlegenden Datenstrukturen vertraut zu sein. Ich habe hier eine Liste vonkleinen Aufgaben zusammengestellt, die Sie in der Datei <em>numpy_basic.py</em> beantworten sollen. <strong>Suchen Sie sich insgesamt 14 (von 23) Sterne zusammen und implementieren Sie diese</strong>. Das ist häufig ein Einzeiler oder Zweizeiler. Die Musterlösung benötigt in jeder Teilaufgabe maximal drei Zeilen. Es muss aber nicht krampfhaft versucht werden diese Vorgabe zu erreichen, dies soll nur ein Hinweis darauf sein, dass Sie keinen langen Code schreiben müssen. Lesen Sie sich selbstständig in die Dokumentation ein und versuchen Sie die Fragen mit den notwendigen Numpy-Funktionen zu beantworten. Sollten Sie keine Funktion finden, implementieren Sie eine Lösung selbst in einer kleinen Funktion. Sie können auch im Kursforum nach Hilfe suchen. <strong>Bitten geben Sie die Lösung jeweils auf der Konsole aus (mittels print)</strong>. Hinweis: die print Anweisung zählt nicht zu dem Einzeiler oder Zweizeiler, wenn im Hinweis also steht <i>geht in einer Zeile</i> muss in dieser nicht auch noch die print Anweisung kommen.</p>

In [64]:
import numpy as np

<p style="margin-left:2em">a) (*) Erzeugen Sie einen Vektor a mit Nullen der Länge 10 (10 Elemente) und setzen den Wert des 5. Elementes auf eine 1.</p>

In [65]:
# Erzeugen Sie einen Vektor mit Nullen der Länge 10 und setzen den Wert des 5. Elementes auf eine 1.
vec1 = np.array([0] * 10)
vec1[4] = 1
print(vec1)

[0 0 0 0 1 0 0 0 0 0]


<p style="margin-left:2em">b) (*) Erzeugen Sie einen Vektor b mit Ganzahl-Werten von 10 bis 49 (geht in einer Zeile).</p>

In [66]:
# Erzeugen Sie einen Vektor mit Ganzzahl-Werten von 10 bis 49 (geht in einer Zeile).
vec2 = np.arange(10, 50)
print(vec2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<p style="margin-left:2em">c) (*) Erzeugen Sie einen Vektor mit 8 Einträgen zwischen -1 und 1 bei dem alle Werte die gleichen Abstände habe und sowohl -1 als auch 1 enthalten sind (geht in einer Zeile).</p>

In [67]:
# Erzeugen Sie einen Vektor mit 8 Einträgen zwischen -1 und 1 bei dem alle Werte die gleichen Abstände habe und sowohl -1 als auch 1 enthalten sind (geht in einer Zeile). Hinweis: guckt euch den Unterschied zwischen numpy.arange und numpy.linspace welche Funktion passt besser?.
vec3 = np.linspace(-1, 1, 8)
print(vec3)

[-1.         -0.71428571 -0.42857143 -0.14285714  0.14285714  0.42857143
  0.71428571  1.        ]


<p style="margin-left:2em">d) (*) Geben Sie nur das Stück (slice) von Vektor b) aus, das die Zahlen 21 bis 38 (Stellen 11 bis 28) beinhaltet (geht in einer Zeile).</p>

In [68]:
# Geben Sie nur das Stück (slice) von Vektor b) aus, das die Zahlen 21 bis 38 (Stellen 11 bis 28) beinhaltet (geht in einer Zeile).
vec4 = vec2[11:29]
print(vec4)

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]


<p style="margin-left:2em">e) (*) Ändern Sie den Vektor b) indem sie das Stück (slice) von Stelle 15 bis <strong>einschließlich</strong> Stelle 25 mit den Werten negierten Werten von Stelle 1 bis <strong>einschließlich</strong> Stelle 11 überschreiben (geht in einer Zeile).</p>

In [69]:
# Ändern Sie den Vektor b) indem sie das Stück (slice) von Stelle 15 bis einschließlich Stelle 25 mit den Werten negierten Werten von Stelle 1 bis einschließlich Stelle 11 überschreiben (geht in einer Zeile).
vec2[15:26] = vec2[1:12] * -1
print(vec2)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24 -11 -12 -13
 -14 -15 -16 -17 -18 -19 -20 -21  36  37  38  39  40  41  42  43  44  45
  46  47  48  49]


<p style="margin-left:2em">f) (*) Drehen Sie die Werte des Vektors aus b) oder a) um (geht in einer Zeile).</p>

In [70]:
# Drehen Sie die Werte des Vektors aus a) oder b) um (geht in einer Zeile).
print(np.flip(vec2))

[ 49  48  47  46  45  44  43  42  41  40  39  38  37  36 -21 -20 -19 -18
 -17 -16 -15 -14 -13 -12 -11  24  23  22  21  20  19  18  17  16  15  14
  13  12  11  10]


<p style="margin-left:2em">g) (*) Summieren Sie alle Werte in einem Array (geht in einer Zeile).</p>

In [71]:
# Summieren Sie alle Werte in einem Array.
print(np.sum(vec2))

674


<p style="margin-left:2em">h) (*) Erzeugen Sie eine 4x4 Matrix mit den Werte 0 (links oben) bis 15 (rechts unten) (geht in einer Zeile).</p>

In [72]:
# Erzeugen Sie eine 4x4 Matrix mit den Werte 0 (links oben) bis 15 (rechts unten) (geht in einer Zeile). Tip: Schauen Sie sich numpy.reshape an
ma1 = np.arange(0, 16).reshape((4, 4))
print(ma1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


<p style="margin-left:2em">i) (*) Erzeugen Sie eine 5x3 Matrix mit Zufallswerteintegers zwischen 0-100 (geht in einer Zeile).</p>

In [73]:
# Erzeugen Sie eine 5x3 Matrix mit Zufallswerteintegers zwischen 0-100 (geht in einer Zeile).
ma2 = np.random.randint(100, size=(5, 3))
print(ma2)

[[50 97 55]
 [44 79 94]
 [21 70 18]
 [ 4 69  7]
 [85 75 53]]


<p style="margin-left:2em">j) (*) Multiplizieren Sie eine 4x3 Matrix mit einer 3x2 Matrix (geht zwar in einer Zeile, aber benutzen Sie lieber Hilfsvariablen und drei Zeilen).</p>

In [74]:
# Multiplizieren Sie eine 4x3 Matrix mit einer 3x2 Matrix (geht zwar in einer Zeile, aber benutzen Sie lieber Hilfsvariablen und drei Zeilen).
ma3 = np.random.randint(0, 10, (4, 3))
ma4 = np.random.randint(0, 10, (3, 2))
print(np.matmul(ma3, ma4))


[[153 144]
 [138 120]
 [ 64  66]
 [ 63  58]]


<p style="margin-left:2em">k) (*) Erzeugen Sie eine 5x5 Matrix und geben Sie jeweils die geraden und die ungeraden Zeile aus (geht jeweils in einer Zeile).</p>

In [75]:
# Erzeugen Sie eine 5x5 Matrix und geben Sie jeweils die geraden und die ungeraden Zeile aus (geht jeweils in einer Zeile).
ma5 = np.random.randint(0, 10, (5, 5))
print(ma5)
print(ma5[ma5 % 2 == 0])
print(ma5[ma5 % 2 == 1])

[[3 7 7 9 3]
 [5 7 0 1 9]
 [1 0 2 3 5]
 [1 7 9 9 2]
 [8 5 3 8 2]]
[0 0 2 2 8 8 2]
[3 7 7 9 3 5 7 1 9 1 3 5 1 7 9 9 5 3]


<p style="margin-left:2em">l) (**) Erzeuge eine 5x5 Matrix mit Zufallswerteintegers zwischen 0-100 und finde deren Maximum und Minimum und normalisieren Sie die Werte (sodass alle Werte zwischen 0 und 1 liegen - ein Wert wird 1 (max) sein und einer 0 (min)).</p>

In [76]:
# Erzeuge eine 5x5 Matrix mit Zufallsintegers zwischen 0-100 und finde deren Maximum und Minimum und normalisieren Sie die Werte (sodass alle Werte zwischen 0 und 1 liegen - ein Wert wird 1 (max) sein und einer 0 (min)).
# Hinweis: D.h. Sie muessen die Werte normalisieren (R - R_min) / (R_max - R_min)
ma6 = np.random.randint(0, 100, (5, 5))
ma6_max = ma6.max()
ma6_min = ma6.min()
print(ma6)
print((ma6 - ma6_min) / (ma6_max - ma6_min))

[[52  0 25 73 81]
 [34  5  2 63 88]
 [54  7 98 42 71]
 [79 70 70 20 39]
 [50 81 52 52 14]]
[[0.53061224 0.         0.25510204 0.74489796 0.82653061]
 [0.34693878 0.05102041 0.02040816 0.64285714 0.89795918]
 [0.55102041 0.07142857 1.         0.42857143 0.7244898 ]
 [0.80612245 0.71428571 0.71428571 0.20408163 0.39795918]
 [0.51020408 0.82653061 0.53061224 0.53061224 0.14285714]]


<p style="margin-left:2em">m) (**) Extrahieren Sie den Integer-Anteil eine Arrays von zufälliger Zahlen zwischen 0-10 auf 3 verschiedene Arten.</p>

In [77]:
# Extrahieren Sie den Integer-Anteil eine Arrays von zufälliger Zahlen zwischen 0-10 auf 3 verschiedene Arten.
ar1 = np.random.random(10) * 10
print(ar1)
print(ar1.astype(int))
print(ar1 // 1)
print(ar1 - ar1 % 1)

[1.16557213 3.4713002  1.01377243 7.92167009 3.74712287 1.65298991
 1.17933798 8.35006703 9.09493264 4.25639026]
[1 3 1 7 3 1 1 8 9 4]
[1. 3. 1. 7. 3. 1. 1. 8. 9. 4.]
[1. 3. 1. 7. 3. 1. 1. 8. 9. 4.]


<p style="margin-left:2em">n) (**) Erzeugen Sie eine Matrix M der Größe 4x3 und einen Vektor v mit Länge 3. Multiplizieren Sie jeden Spalteneintrag aus mit der kompletten Spalte aus M. Nutzen Sie dafür Broadcasting.</p>

In [78]:
# Erzeugen Sie eine Matrix $M$ der Größe 4x3 und einen Vektor $v$ mit Länge 3. Multiplizieren Sie jeden Spalteneintrag aus $v$ mit der kompletten Spalte aus $M$. Nutzen Sie dafür Broadcasting.
m = np.random.randint(0, 10, (4, 3))
v = np.random.randint(0, 10, 3)
print(m + v)

[[ 9 10 10]
 [11  3 13]
 [ 7  3  8]
 [11  3 15]]


<p style="margin-left:2em">o) (***) Erzeugen Sie einen Zufallsmatrix der Größe 10x2, die Sie als Kartesische Koordinateninterpretieren können ([[x0, y0],[x1, y1],[x2, y2]]). Konvertieren Sie diese in Polarkoordinaten <a href="https://de.wikipedia.org/wiki/Polarkoordinaten">https://de.wikipedia.org/wiki/Polarkoordinaten</a>.</p>

In [79]:
# Erzeugen Sie einen Zufallsmatrix der Größe 10x2, die Sie als Kartesische Koordinaten interpretieren können ([[x0, y0],[x1, y1],[x2, y2]]).
# Konvertieren Sie diese in Polarkoordinaten \url{https://de.wikipedia.org/wiki/Polarkoordinaten}.
# Hinweis: nutzen Sie fuer die Berechnung des Winkel np.arctan2 und geben Sie jeweils Radius und Winkel als Vektor aus
import math

for i in np.random.randint(0, 10, (10, 2)):
    print(i)
    print([math.sqrt(i[0] ** 2 + i[1] ** 2), np.arctan2(i[0], i[1])])

[4 6]
[7.211102550927978, 0.5880026035475675]
[2 9]
[9.219544457292887, 0.21866894587394195]
[7 5]
[8.602325267042627, 0.9505468408120752]
[4 9]
[9.848857801796104, 0.4182243295792291]
[6 8]
[10.0, 0.6435011087932844]
[2 7]
[7.280109889280518, 0.27829965900511133]
[6 9]
[10.816653826391969, 0.5880026035475675]
[5 9]
[10.295630140987, 0.507098504392337]
[5 3]
[5.830951894845301, 1.0303768265243125]
[5 4]
[6.4031242374328485, 0.8960553845713439]


<p style="margin-left:2em">p) (***) Erzeugen Sie einen Matrix der Größe 6x2, die Sie als Kartesische Koordinaten interpretieren können ([[x0, y0],[x1, y1],[x2, y2]]). Schreiben Sie eine Funktion, die alle Punkt-Punkt Abstände berechnet und in einer 6x6 Matrix ausgibt.</p>

In [80]:
# Erzeugen Sie einen Matrix der Größe 6x2, die Sie als Kartesische Koordinaten interpretieren können ([[x0, y0],[x1, y1],[x2, y2]]).
# Schreiben Sie eine Funktion, die alle Punkt-Punkt Abstände berechnet.
ma7 = np.random.randint(0, 10, (6, 2))
print(ma7)
i = j = 0
ma9 = np.array([[0.0] * 6] * 6)
for x in ma7:
    for y in ma7:
        ma9[i, j] = np.linalg.norm(x - y, ord=2)
        j += 1
    j = 0
    i += 1
print(ma9)

[[0 9]
 [2 2]
 [9 4]
 [7 2]
 [1 9]
 [1 2]]
[[ 0.          7.28010989 10.29563014  9.89949494  1.          7.07106781]
 [ 7.28010989  0.          7.28010989  5.          7.07106781  1.        ]
 [10.29563014  7.28010989  0.          2.82842712  9.43398113  8.24621125]
 [ 9.89949494  5.          2.82842712  0.          9.21954446  6.        ]
 [ 1.          7.07106781  9.43398113  9.21954446  0.          7.        ]
 [ 7.07106781  1.          8.24621125  6.          7.          0.        ]]
